
// Objective-C API for talking to the following Go packages
//
//	github.com/xjasonlyu/tun2socks/v2/bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tun2Socks_FRAMEWORK_H__
#define __Tun2Socks_FRAMEWORK_H__

#include "Bridge.objc.h"
#include "Universe.objc.h"

#endif
