name: CI

on:
  push:
    branches:
      - main
      - relative-protocol-package
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why run the workflow manually?'
        required: false
        default: 'manual trigger'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Print Swift toolchain version
        run: swift --version

      - name: Resolve Swift package dependencies
        run: swift package resolve

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: RelativeProtocol ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Build the Leaf xcframework locally by running:

            ```
            ./Scripts/build.sh
            ```
